server:
  port: 8101
spring:
  application:
    name: config
  profiles:
    active: dev
  cloud:
    config:
      server:
        git:
          uri:  https://github.com/CloneableX/spring-cloud-study.git
          search-paths: news_repo
          username: CloneableX
          # TODO 上传时隐去密码
          password: ******
      label: master
eureka:
  instance:
    hostname: ${spring.cloud.client.ipAddress}
    instance-id: ${spring.cloud.client.ipAddress}:${server.port}
  client:
    service-url:
      defaultZone: http://localhost:8888/eureka/