server:
  port: 8080
mysql:
  datasource:
    test1:
      url: jdbc:mysql://localhost:3306/test01?useUnicode=true&characterEncoding=utf-8
      username: root
#      TODO 上传时隐藏密码
      password: ******
      minPoolSize: 3
      maxPoolSize: 25
      maxLifeTime: 20000
      borrowConnectTimeout: 30
      loginTimeout: 30
      maintenanceInterval: 60
      maxIdleTime: 60
      testQuery: select 1
    test2:
      url: jdbc:mysql://localhost:3306/test02?useUnicode=true&characterEncoding=utf-8
      username: root
#      TODO 上传时隐藏密码
      password: ******
      minPoolSize: 3
      maxPoolSize: 25
      maxLifeTime: 20000
      borrowConnectTimeout: 30
      loginTimeout: 30
      maintenanceInterval: 60
      maxIdleTime: 60
      testQuery: select 1