server:
  port: 8080
eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka/
spring:
  application:
    name: gateway
zuul:
  routes:
    api:
      path: /api/**
      serviceId: hello